### ISSUE TITLE
bluetooth now prevents using UART console

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-project/nerves_system_rpi3#109]
on raspberry pi 3 the following things all changed:
* `/dev/serial0` is no longer a thing (?)
* `/dev/ttyACM0` no longer exists and seems to have been replaced with `/dev/ttyS0`
* `dtoverlay=pi3-disable-bt` is now required to use the uart console
   * `pi3-miniuart-bt` will allow sending data from the pi, but the pi won't actually accept data

Information gathered from [here](https://elinux.org/RPi_Serial_Connection) and [here](https://www.raspberrypi.org/documentation/configuration/uart.md)

**Comment by ConnorRigby** [comment]
Fixed in a custom system here: https://github.com/FarmBot-Labs/farmbot_system_rpi3/commit/56d47091142b87c811cb5257434db9771b6dd03f

**Comment by fhunleth** [comment]
Where do you see that `serial0` is not a thing or that `pi3-miniuart-bt` no longer works?

**Comment by fhunleth** [comment]
Here are the official docs: https://github.com/raspberrypi/documentation/blob/master/configuration/uart.md.

**Comment by ConnorRigby** [comment]
Sorry for the noise. my system was built with rpi-firmware from an old kernel version for some reason.
