### ISSUE TITLE
Ethernet sometimes fails to come up

### ISSUE THREAD

**Issue by axelson** [nerves-project/nerves_system_rpi3#115]
### Environment

* Elixir version (`elixir -v`): Elixir 1.9.0 (compiled with Erlang/OTP 22)
* Nerves environment: (`mix nerves.env --info`): 
```
|nerves_bootstrap| Environment Package List

  Pkg:         nerves_toolchain_ctng
  Vsn:         1.6.0
  Type:        toolchain_platform
  BuildRunner: {nil, []}

  Pkg:         nerves_system_br
  Vsn:         1.8.2
  Type:        system_platform
  BuildRunner: {nil, []}

  Pkg:         nerves_toolchain_arm_unknown_linux_gnueabihf
  Vsn:         1.2.0
  Type:        toolchain
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

  Pkg:         nerves_system_rpi3
  Vsn:         1.8.0
  Type:        system
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

|nerves_bootstrap| Loadpaths Start


Nerves environment
  MIX_TARGET:   rpi3
  MIX_ENV:      dev

|nerves_bootstrap| Environment Variable List
  target:     rpi3
  toolchain:  /home/jason/.nerves/artifacts/nerves_toolchain_arm_unknown_linux_gnueabihf-linux_x86_64-1.2.0
  system:     /home/jason/.nerves/artifacts/nerves_system_rpi3-portable-1.8.0
  app:        /home/jason/dev/scenic-side-screen/fw
|nerves_bootstrap| Loadpaths End
```
* Additional information about your host, target hardware or environment that
  may help
  * RPI3 with official raspberry pi touch screen
  * Running the code from: https://github.com/axelson/scenic-side-screen (see the fw folder)

### Current behavior

Ethernet correctly comes up approximately 90% of the time, but fails to come up the rest.

Logs when Ethernet is not working:
https://gist.github.com/axelson/278400fec17dda89b979ea226f670db3

Logs when Ethernet is working:
https://gist.github.com/axelson/80eb528e6ef07c642c1f700f1f35eba0

One of the logs that might be key that is missing in the "not working case":
```
nerves_network_interface received :ifchanged and %{ifname: "eth0", index: 2, is_broadcast: true, is_lower_up: true, is_multicast: true, is_running: true, is_up: true, mac_address: "b8:27:eb:23:7b:9e", mac_broadcast: "ff:ff:ff:ff:ff:ff", mtu: 1500, operstate: :up, stats: %{collisions: 0, multicast: 0, rx_bytes: 0, rx_dropped: 0, rx_errors: 0, rx_packets: 0, tx_bytes: 0, tx_dropped: 0, tx_errors: 0, tx_packets: 0}, type: :ethernet}
```

dmesg output page 1:
![2019-07-31 08 44 36](https://user-images.githubusercontent.com/9973/62239571-d7d0b880-b370-11e9-948b-abd77cee3e59.jpg)

dmesg output page 2:
![2019-07-31 08 47 55](https://user-images.githubusercontent.com/9973/62239589-de5f3000-b370-11e9-9c73-e287c44c8520.jpg)

ifconfig output:
```
eth0: flags=[:broadcast, :multicast]
    hwaddr b8:27:eb:23:7b:9e
```

### Expected behavior

Ethernet comes up reliably

Note: I will try updating to the absolute latest versions of nerves_system_rpi3 and nerves_system_br to get the latest buildroot and kernel updates to see if that makes a difference.

Edit: getting the same error after upgrading:
```
nerves 1.5.0 => 1.5.1
nerves_system_br 1.8.2 => 1.8.5
nerves_system_rpi3 1.8.0 => 1.8.2
```

**Comment by fhunleth** [comment]
😭 I was really hoping that updating to the latest Linux kernel would improve things.

Does removing the Ethernet cable and re-inserting it change anything?

Do you have another Raspberry Pi to try? I want to eliminate hardware being an issue.

**Comment by axelson** [comment]
Removing the cable and re-inserting doesn't help :/
I may have another Pi but I'll have to dig for it a little

**Comment by fhunleth** [comment]
Doesn't help you yet, but I have an RPi 3 B+ that I've had on for the past 3 days. Ethernet is still working. @ConnorRigby and @mobileoverlord - have you seen anything like this with the RPi's that you've deployed at your companies?

**Comment by axelson** [comment]
Actually turns out I only have one Raspberry PI 3 (although I do have other older Pi's). Also the symptom I see is that the ethernet never comes up at on on some boots, it's not that it drops after being up (I mention this because you report your test of having the Pi up for 3 days where the 3 days doesn't seem to matter in regards to the issue that I'm seeing).

I can work around it well enough by adding a reboot button to my touch screen but it's still annoying when the ethernet doesn't come up. If it's not a more widespread problem with other people's pi's than it may just be a flaky hardware problem, hopefully not self-imposed by keeping it running with the touchscreen for many days at a time (although the touchscreen was sleeping most of the time).

**Comment by fhunleth** [comment]
See #219 and #220. I'm going to optimistically say that this will be fixed in the next release.

**Comment by axelson** [comment]
:+1: It may have been fixed earlier as well. I haven't seen this in 8-12 months or more.
