### ISSUE TITLE
Use f2fs for /root as rpi4?

### ISSUE THREAD

**Issue by samuelventura** [nerves-project/nerves_system_rpi3#277]
Is there a reason for keeping this system on ext4?

**Comment by fhunleth** [comment]
The main reason is that none of us felt strongly enough to submit a PR to update it. If it's upgraded, we still need ext4 support for devices already using it since the application data partition is formatted on first boot.

**Comment by samuelventura** [comment]
Are there any efforts to provide a safe OTA upgrade mechanism for the /root partition?

**Comment by fhunleth** [comment]
No, `/root` is left to the application to manage.

**Comment by samuelventura** [comment]
Fair enough. Thank you.
