### ISSUE TITLE
Support for rpi 3 model B+

### ISSUE THREAD

**Issue by areel** [nerves-project/nerves_system_rpi3#41]
Hi

Appreciate the model has just been released but thought it worth mentioning.

I have recently purchased a rpi 3 model B+ and have tried to load the Blinky sample app.
The boot process gets as far as the colored screen with a lightening icon on the right hand side.
Using the same boot sdcard on a rpi 3 model B works without issue.

Regards

Aidan

**Comment by fhunleth** [comment]
Thanks for opening the issue. We need to include an additional device tree file to support the RPi3 B+. We may need more things. I don't have one, so I haven't tried adding support yet. If you want to experiment, there should be a .dtb file in the FAT partition on Raspbian that has rpi3b_plus or something like that in its name. Try copying that over to the FAT filesystem that Nerves made.

**Comment by areel** [comment]
I had created a raspbian boot disk and it did have a file named bcm2710-rpi-3-b-plus.dtb.
I copied that file to the BOOT-A drive on the nerves boot disk.
But same issue: sitting on colored screen.

I am happy to test additional files.

**Comment by fhunleth** [comment]
Bummer. I guess that you could try copying over `bootcode.bin`, `fixup.dat` and `start.elf`, but I think that I'll have to update things more methodically when I get a board.

**Comment by areel** [comment]
Tried those.
Still hanging on colored screen but the lightening icon is no longer displayed

**Comment by fhunleth** [comment]
Double bummer. Fwiw, the lightning bolt is an indication that your power supply might not be adequate.

**Comment by fhunleth** [comment]
I finally got a Raspberry Pi 3 B+. It looks like I have everything working - boots, UART, Ethernet, WiFi, and probably BT (didn't check, though). Once https://github.com/nerves-project/nerves_system_br/pull/139 is merged and a new version of `nerves_system_br` is released, I'll be ready to merge the `linux-4.9` branch on this project. This part shouldn't take long. I just need to get some reviews on my changes and we'll be ready to go.

**Comment by mobileoverlord** [comment]
I've been testing this out. Wifi works, but is power hungry. Just to note that it seems that networking on this board requires that it is powered from an external power supply. It will reboot if you are powering it off USB. I think its good to go though.

**Comment by fhunleth** [comment]
In 1.0.0-rc.2: https://github.com/nerves-project/nerves_system_rpi3/releases/tag/v1.0.0-rc.2
