### ISSUE TITLE
Use same serial port configuration as nerves_system_rpi0

### ISSUE THREAD

**Issue by stefan991** [nerves-project/nerves_system_rpi3#43]
Raspberry Pi models with bluetooth chip on the board have the serial ports hooked up differently.

By default if there is a bluetooth chip it is connected with "/dev/ttyAMA0". The other serial "/dev/ttyS0" is then used for the pin headers instead of "dev/ttyAMA0".

The mini UART ("dev/ttyS0") has some downsides compared tho the primary UART ("dev/ttyAMA0"), see last paragraph on this site: https://www.raspberrypi.org/documentation/configuration/uart.md

nerves_system_rpi0 does [load a device tree overlay](https://github.com/nerves-project/nerves_system_rpi0/blob/1266ed9f28d498ca8132b81a85b2dc961a9771f5/config.txt#L29) (pi3-miniuart-bt) to switch the ports back so that the primary serial port is hooked up to the pin headers like on raspberry's without bluetooth onboard.

To be consistent with nerves_system_rpi0 this system should load the same device tree overlay.

I think the serial port gets used more often than the bluetooth chip, so the default config should be that the primary UART is wired to the pin headers. This would mean that every raspberry pi system could use the same serial port by default.
If someone want's to use the bluetooth chip with "dev/ttyAMA0" configuring this is possible via a custom fwup.conf/config.txt.

**Comment by fhunleth** [comment]
This makes sense to me. Could you make a PR with the actual change and test it on a RPi 3 B and RPi 3 B+? If you don't have one or the other one, let us now and we'll test it there.

**Comment by fhunleth** [comment]
Thanks! No rush on the PR. I have a B+, so I can try it out there to make sure there are no surprises. (I don't expect any)
