### ISSUE TITLE
uart console comment is wrong

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-project/nerves_system_rpi3#45]
https://github.com/nerves-project/nerves_system_rpi3/blob/master/rootfs_overlay/etc/erlinit.config#L8

should be `ttyS0`

**Comment by fhunleth** [comment]
See https://github.com/nerves-project/nerves_system_rpi3/commit/a191f3247ec758c7d646af019d79df96c7e3bb18

**Comment by fhunleth** [comment]
@ConnorRigby I verified that `ttyAMA0` works. I think the issue was that that particular commit hasn't been released yet so you had to manually build to get it.

**Comment by ConnorRigby** [comment]
OHhhh i was unaware of that. :+1:
