### ISSUE TITLE
Incompatible with newest version of Relx

### ISSUE THREAD

**Issue by royveshovda** [nerves-project/nerves_system_rpi3#5]
I am not sure of the root cause of the issue, but if you run:
mix nerves.new hello_rpi3 --target rpi3
cd hello_rpi3
mix deps.get
mix compile
mix firmware

you get an error saying the following:
** (CaseClauseError) no case clause matching: :eacces
    lib/exrm/utils/utils.ex:110: ReleaseManager.Utils.relx/5
    lib/mix/tasks/release.ex:339: anonymous fn/4 in Mix.Tasks.Release.do_release/1
    lib/ex_unit/capture_io.ex:146: ExUnit.CaptureIO.do_capture_io/2
    lib/ex_unit/capture_io.ex:119: ExUnit.CaptureIO.do_capture_io/3
    lib/mix/tasks/release.ex:338: Mix.Tasks.Release.do_release/1
    lib/mix/tasks/release.ex:78: Mix.Tasks.Release.do_run/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    lib/mix/tasks/firmware.ex:27: Mix.Tasks.Firmware.run/1

I managed to fix this issue by pinning relx and erlware_commons to the previous version (they release a new version 27.11) with these lines in deps:
{:relx, " ~ > 3.21", override: true},
{:erlware_commons, "~> 0.21.0", override: true}

I have reproduced this on target=rpi also.

I am running this on macOS.

**Comment by mobileoverlord** [comment]
This issue has been solved by the core nerves package switching to distillery. Please update to using the latest `:nerves ~> 0.4.0`

**Comment by royveshovda** [comment]
Perfect. Just wanted to notify you guys of the issue. But now I see it is resolved. Nice work.
