### ISSUE TITLE
Pi camera?

### ISSUE THREAD

**Issue by LTheGreats** [nerves-project/nerves_system_rpi3#7]
I want to make a robot using the rpi 3 and I want to use the pi camera but I do not know how to use it with nerves.

**Comment by fhunleth** [comment]
The official raspberry pi camera commands are included in the default Nerves rpi3 system image so you can call them directly. Here are the docs for the commands: https://www.raspberrypi.org/documentation/usage/camera/raspicam/

Another option is https://github.com/fhunleth/raspijpgs. A while back, I wasn't happy with the Raspberry Pi commands for streaming motion JPEG and how they interfaced with the Erlang VM, so I wrote this. I haven't updated raspijpegs in a while, so you may need to debug it (not sure if there's been code rot or not).
